/* eslint-disable */
// @generated by scripts/generate-plugin-registry.mjs — NICHT von Hand bearbeiten.
// Quelle: plugins/packages/*/manifest.json. Neu erzeugen: npm run generate:plugins

import dynamic from 'next/dynamic';
import type { PluginComponentProps, PluginWebModule } from './registry-types';
import example_de from '@kompetenzhub/plugin-example/i18n/de.json';
import example_fr from '@kompetenzhub/plugin-example/i18n/fr.json';
import example_it from '@kompetenzhub/plugin-example/i18n/it.json';
import example_en from '@kompetenzhub/plugin-example/i18n/en.json';
import memo_de from '@kompetenzhub/plugin-memo/i18n/de.json';
import memo_fr from '@kompetenzhub/plugin-memo/i18n/fr.json';
import memo_it from '@kompetenzhub/plugin-memo/i18n/it.json';
import memo_en from '@kompetenzhub/plugin-memo/i18n/en.json';

export const pluginWebRegistry: Record<string, PluginWebModule> = {
  example: {
    pages: {
      '/': dynamic<PluginComponentProps>(() => import('@kompetenzhub/plugin-example/web/ExamplePage'), { ssr: false }),
    },
    widgets: {
      'teacher.dashboard': [dynamic<PluginComponentProps>(() => import('@kompetenzhub/plugin-example/web/ExampleWidget'), { ssr: false })],
    },
    components: {},
    translations: {
      de: example_de,
      fr: example_fr,
      it: example_it,
      en: example_en,
    },
  },
  memo: {
    pages: {
      '/': dynamic<PluginComponentProps>(() => import('@kompetenzhub/plugin-memo/web/MemoOverviewPage'), { ssr: false }),
    },
    widgets: {
      'teacher.dashboard': [dynamic<PluginComponentProps>(() => import('@kompetenzhub/plugin-memo/web/MemoDashboardWidget'), { ssr: false })],
    },
    components: {
      MemoButton: dynamic<PluginComponentProps>(() => import('@kompetenzhub/plugin-memo/web/MemoButton'), { ssr: false }),
      MemoTab: dynamic<PluginComponentProps>(() => import('@kompetenzhub/plugin-memo/web/MemoTab'), { ssr: false }),
    },
    translations: {
      de: memo_de,
      fr: memo_fr,
      it: memo_it,
      en: memo_en,
    },
  },
};
