server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Das ist der Zaubertrick:
    # Egal welcher Pfad aufgerufen wird ($uri), Nginx versucht ihn zu finden.
    # Wenn er ihn nicht findet, leitet er ohne URL-Änderung an /index.html weiter.
    location / {
        try_files $uri $uri/ /index.html;
    }
}